apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-cloudexplorer
  name: {{ .Release.Name }}-cloudexplorer-service
spec:
  type: {{ .Values.cloudexplorer.service.type }}
  ports:
    - name: "cloudexplorer-80"
      port: {{ .Values.cloudexplorer.service.port }}
      targetPort: {{ .Values.cloudexplorer.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-cloudexplorer