apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Release.Name }}-cloudexplorer
  name: {{ .Release.Name }}-cloudexplorer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cloudexplorer.pvc.storage }}