apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-cloudexplorer-elasticsearch
  name: {{ .Release.Name }}-cloudexplorer-elasticsearch-service
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app: {{ .Release.Name }}-cloudexplorer-elasticsearch-statefulset
