apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-cloudexplorer-mysql
  name: {{ .Release.Name }}-cloudexplorer-mysql-service
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: {{ .Release.Name }}-cloudexplorer-mysql-statefulset