apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-cloudexplorer-redis
  name: {{ .Release.Name }}-cloudexplorer-redis-service
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: {{ .Release.Name }}-cloudexplorer-redis-deployment
